require "rails_helper"

# Minimal notifier for constraint probes — no delivery methods needed.
# Top-level constants are required here: Noticed v2's Event#inherited hook
# fires immediately and registers the STI type, which only works at top-level
# scope. The `unless defined?` guards prevent collision when the suite reloads.
class TestNotifier < Noticed::Event; end unless defined?(TestNotifier)

# TestNotifier::Notification is auto-generated by noticed's inherited hook,
# but we alias it here for readability in the spec.
TestNotification = TestNotifier::Notification unless defined?(TestNotification)

RSpec.describe "Noticed hardening" do
  let(:event) { TestNotifier.create!(idempotency_key: SecureRandom.hex(8)) }

  describe "idempotency_key partial unique index" do
    it "raises RecordNotUnique on duplicate (idempotency_key) when both are non-NULL" do
      TestNotifier.create!(idempotency_key: "key-dup-1")
      expect {
        TestNotifier.create!(idempotency_key: "key-dup-1")
      }.to raise_error(ActiveRecord::RecordNotUnique)
    end

    it "allows multiple events with idempotency_key: nil (partial index excludes NULLs)" do
      TestNotifier.create!(idempotency_key: nil)
      expect {
        TestNotifier.create!(idempotency_key: nil)
      }.not_to raise_error
    end
  end

  describe "noticed_notifications.event_id cascade FK" do
    it "destroys child notifications when the parent event is destroyed" do
      user = create(:user)
      TestNotification.create!(event_id: event.id, recipient: user)
      expect { event.destroy! }.to change(Noticed::Notification, :count).by(-1)
    end
  end

  describe "recipient_type_user_only_v1 check constraint" do
    it "rejects non-User recipient_type" do
      workspace = create(:workspace)
      expect {
        TestNotification.create!(event_id: event.id,
                                 recipient_type: "Workspace", recipient_id: workspace.id)
      }.to raise_error(ActiveRecord::StatementInvalid, /CHECK constraint failed: recipient_type_user_only_v1/)
    end
  end

  describe "seen_before_read check constraint" do
    it "rejects read_at < seen_at" do
      user = create(:user)
      now = Time.current
      expect {
        TestNotification.create!(event_id: event.id, recipient: user,
                                 seen_at: now, read_at: now - 1.hour)
      }.to raise_error(ActiveRecord::StatementInvalid, /CHECK constraint failed: seen_before_read/)
    end
  end

  describe "partial unread index" do
    it "exists with the correct WHERE clause" do
      indexes = ActiveRecord::Base.connection.indexes("noticed_notifications")
      unread = indexes.find { |i| i.name == "index_noticed_notifications_unread" }
      expect(unread).not_to be_nil
      expect(unread.where).to include("read_at IS NULL")
    end
  end
end
